### ISSUE TITLE
'super' object has no attribute 'form_valid'

### ISSUE THREAD

**Issue by OmarGonD** [Valian/django-multiple-forms#1]
Hi, just found your gist, and I think it can help me out. the thing is that when using according to your blog but I'm getting:

`'super' object has no attribute 'form_valid'`

I've commented the method: 'def get_forms_classes(self)" as I don't need to make restrictions based on user status. 

You may be wondering, "there is only one form there: "ReferenciaForm". My Issue is that I need to make a form for every "Referencia" (spanish for reference) object inside "nucleo_referencia" table. I would appreciate if you could point me to the correct query to this to  work with your gist. Thanks.

**views.py**
```

class MultipleFormsDemoView(MultipleFormsView):
    template_name = 'app_administrador/validar-referencias-nana.html'
    success_url = '/'

    # here we specify all forms that should be displayed
    forms_classes = [
        ReferenciaForm
    ]

    # def get_forms_classes(self):
    #     # we hide staff_only forms from not-staff users
    #     # our goal no. 3 about dynamic amount list of forms
    #     forms_classes = super(MultipleFormsDemoView, self).get_forms_classes()
    #     user = self.request.user
    #     if not user.is_authenticated() or not user.is_staff:
    #         return list(filter(lambda form: not getattr(form, 'staff_only', False), forms_classes))
    #     return forms_classes

    def form_valid(self, form):
        print("yay it's valid!")
        return super(MultipleFormsDemoView).form_valid(form)
```
  
Also, I'm noticing that the last line in your gist is: 

```
class MultipleFormsView(TemplateResponseMixin, MultipleFormsMixin, ProcessFormView):
    pass
```
As it has `pass`, I'm wondering if we should write something there... and this is the class I'm using in my view file:

```
# View with multiple forms, inheriting our Generic MultipleFormsView
class MultipleFormsDemoView(MultipleFormsView):
```

**Comment by Valian** [comment]
Hi @OmarGonD. This repository may be a bit outdated. It's tested with the previous version of Django, but probably it should still be working.

We're using `pass`, because we're creating a class without body, just using inherited methods and properties.

About your error: There is no `self` in `super()` call. Try to add it, like this:

``` python
class MultipleFormsView(TemplateResponseMixin, MultipleFormsMixin, ProcessFormView):
    pass

class MultipleFormsDemoView(MultipleFormsView):
    template_name = 'app_administrador/validar-referencias-nana.html'
    success_url = '/'

    # here we specify all forms that should be displayed
    forms_classes = [
        ReferenciaForm
    ]

    def form_valid(self, form):
        print("yay it's valid!")
        # add it here
        return super(MultipleFormsDemoView, self).form_valid(form)

        # if you're using python 3, you may omit arguments in super call
        # return super().form_valid(form)
```

It should be working. If not, give me a sign. 

PS. I see that there is a bug on my blog, I'll fix it. Thanks!
